version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: my_db
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: my_user
      # You can use whatever password you like
      POSTGRES_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: